config/routes.rb
Rails.application.routes.draw do
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  root to: "public/homes#top"
  get "about" => "public/homes#about"
  get "customers/my_page" => "public/customers#show"
  get "customers/information/edit" => "public/customers#edit"
  patch "customers" => "public/customers#update"

  namespace :public do
    resources :items, only: [:index, :show]
  end

  namespace :public do
    resources :customers, only: [:show, :edit, :update] do
      collection do
        get 'check'
        patch 'withdraw'
      end
    end
  end

  namespace :public do
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete 'all_destroy'
      end
    end
  end

  namespace :public do
    resources :orders, only: [:index, :new, :show, :create] do
      collection do
        get 'complete'
        post 'check'
      end
    end
  end

  get "admin" => "admin/homes#top"
  namespace :admin do
    resources :items
  end
  namespace :admin do
    resources :customers
  end
  namespace :admin do
    resources :orders, only: [:show]
  end
end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :image

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
  

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(item_params)

    @item.save
    redirect_to admin_items_path
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :image)
  end

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<%= render 'admin/list' %>
<div class="container">
  <div class="row">
    <div class="col-4">
      <h3>商品編集</h3>
    </div>
  </div>

  <%= form_with model: @item, url: admin_item_path do |f| %>
  <div class="row">
    <div class="col-1">
        商品画像
      </div>
      <div class="col-10">
        <%= f.file_field :image, placeholder: "画像", accept: "image/*" %>
      </div>
    </div>

    <div class="row">
      <div class="col-1">
        商品名
      </div>
      <div class="col-10 mt-1">
        <p><%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前" %></p>
      </div>
    </div>

    <div class="row">
      <div class="col-1">
        商品説明
      </div>
      <div class="col-10">
        <p><%= f.text_area :introduction, autofocus: true %></p>
      </div>
    </div>

    <div class="row">
      <div class="col-1">
        税抜価格
      </div>
      <div class="col-10">
        <p><%= f.text_field :price, autofocus: true %>円</p>
      </div>
    </div>

    <%= f.submit "変更を保存" %>
  <% end %>
  </div>


</div>

app/views/admin/items/index.html.erb
<%= render 'admin/list' %>
<div class="container">
  <div class="row">
    <div class="col-3">
      <h5>商品一覧</h5>
    </div>
    <div class="col-6">
        <a class="btn btn-success rounded-circle p-0" style="width:2rem;height:2rem;" href="/admin/items/new" role="button">+</a>
    </div>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th>商品ID</th>
        <th>商品名</th>
        <th>税抜価格</th>
      </tr>
    </thead>
    <% @items.each do |item| %>
    <tbody>
        <td><%= item.id %></td>
        <td><%= link_to item.name, admin_item_path(item.id) %></td>
        <td><%= item.price %></td>
    </tbody>
    <% end %>
  </table>
  <%= paginate @items %>
</div>

app/views/admin/items/new.html.erb
<%= render 'admin/list' %>

<div class="container">
  <div class="row">
    <div class="col-3">
      <h5>商品新規登録</h5>
    </div>
  </div>

  <%= form_with model: @item, url: admin_items_path do |f| %>
    <div class="row">
      <div class="col-2">
        商品画像
      </div>
      <div class="col-4">
        <div class="mb-2">
        <%= f.file_field :image, accept: "image/*" %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-2">
        商品名
      </div>
      <div class="col-8">
        <div class="mb-2">
        <%= f.text_field :name %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-2">
        商品説明
      </div>
      <div class="col-8">
        <div class="mb-2">
        <%= f.text_area :introduction %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-2">
        税抜き価格
      </div>
      <div class="col-8">
        <%= f.text_field :price %>
      </div>
    </div>
    <%= f.submit '新規登録' %>
  <% end %>
</div>

app/views/admin/items/show.html.erb
<%= render 'admin/list' %>
<div class="container">
  <div class="row">
    <div class="col-3">
      <h3>商品詳細</h3>
    </div>
  </div>

  <div class="row">
    <div class="col-6">
      <%= image_tag @item.get_image %>
    </div>
    <div class="col-6">
      <p>商品名　<%= @item.name %></p>
      <p>商品説明　<%= @item.introduction %></p>
      <p>税込価格　<%= @item.price %>円</p>
    </div>
  </div>

  <div class="row">
      <div class="mx-auto">
        <%= link_to "編集する", edit_admin_item_path(@item.id), class: 'btn btn-success' %>
      </div>
  </div>
</div>