config/routes.rb
Rails.application.routes.draw do
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  root to: "public/homes#top"
  get "about" => "public/homes#about"
  get "customers/my_page" => "public/customers#show"
  get "customers/information/edit" => "public/customers#edit"
  patch "customers" => "public/customers#update"

  namespace :public do
    resources :items, only: [:index, :show]
  end

  namespace :public do
    resources :customers, only: [:show, :edit, :update] do
      collection do
        get 'check'
        patch 'withdraw'
      end
    end
  end

  namespace :public do
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete 'all_destroy'
      end
    end
  end

  namespace :public do
    resources :orders, only: [:index, :new, :show, :create] do
      collection do
        get 'complete'
        post 'check'
      end
    end
  end

  get "admin" => "admin/homes#top"
  namespace :admin do
    resources :items
  end
  namespace :admin do
    resources :customers
  end
  namespace :admin do
    resources :orders, only: [:show]
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   has_many :cart_items, dependent: :destroy
   has_many :orders

  def full_name
    self.first_name + " " + self.last_name
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end
  def show
    @customer = Customer.find(params[:id])
  end
  def edit
    @customer = Customer.find(params[:id])
  end
  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer.id)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<%= render 'admin/list' %>
<div class="container">
  <div class="row">
    <div class="col-6">
      <h4><strong><%= @customer.full_name %></strong>さんの<strong>会員情報編集</strong></h4>
    </div>
  </div>

  <%= form_with model: @customer, url: admin_customer_path do |f| %>
  <div class="row">
    <div class="col-2">
      <p>会員ID</p>
    </div>
    <div class="col-10">
      <p><%= @customer.id %></p>
    </div>
  </div>

  <div claas="row">
    <div class="form-inline">
      <div class="col-2">
        <p>氏名</p>
        <p>フリガナ</p>
      </div>
      <div class="col-auto">
        <p><%= f.text_field :first_name, autofocus: true %></p>
        <p><%= f.text_field :first_name_kana, autofocus: true %></p>
      </div>
      <div class="col-auto">
        <p><%= f.text_field :last_name, autofocus: true %></p>
        <p><%= f.text_field :last_name_kana, autofocus: true %></p>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-2 mt-4">
       <p>郵便番号</p>
       <p>住所</p>
       <p>電話番号</p>
       <p>メールアドレス</p>
       <p>会員ステータス</p>
    </div>
    <div class="col-10">
      <p><%= f.text_field :postal_code, autofocus: true %></p>
      <p><%= f.text_field :address, autofocus: true %></p>
      <p><%= f.text_field :telephone_number, autofocus: true %></p>
      <p><%= f.text_field :email, autofocus: true %></p>
    　<label for="r_male">有効
    　  <input id="1" type="radio" name="gender" value="有効">
    　</label>
    　<label for="r_male">退会
    　  <input id="1" type="radio" name="gender" value="退会">
    　</label>
    　<p><%= f.submit "変更を保存する" %></p>
    </div>
  </div>
  <% end %>
</div>

app/views/admin/customers/index.html.erb
<%= render 'admin/list' %>
<div class="container">
  <div class="row">
    <div class="col-2">
      <h5>会員一覧</h5>
    </div>
  </div>


  <div class="row">
    <table class="table">
      <thead>
        <tr>
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <% @customers.each do |customer| %>
      <tbody>
        <td><%= customer.id %></td>
        <td><%= link_to customer.full_name, admin_customer_path(customer.id) %></td>
        <td><%= customer.email %></td>
        <td><%= customer.is_deleted %></td>
      </tbody>
      <% end %>
    </table>
  </div>
</div>

app/views/admin/customers/show.html.erb
<%= render 'admin/list' %>
<div class="container">
  <div class="row">
    <div class="col-4">
      <h4><strong><%= @customer.full_name %></strong>さんの<strong>会員詳細</strong></h4>
    </div>
  </div>

  <div class="row">
    <div class="col-2">
      <p>会員ID</p>
      <p>氏名</p>
      <p>フリガナ</p>
      <p>郵便番号</p>
      <p>住所</p>
      <p>電話番号</p>
      <p>メールアドレス</p>
      <p>会員ステータス</p>
    </div>
    <div class="col-10">
      <p><%= @customer.id %></p>
      <p><%= @customer.first_name %> <%= @customer.last_name %></p>
      <p><%= @customer.first_name_kana %> <%= @customer.last_name_kana %></p>
      <p><%= @customer.postal_code %></p>
      <p><%= @customer.address %></p>
      <p><%= @customer.telephone_number %></p>
      <p><%= @customer.email %></p>
      <p><%= @customer.is_deleted %></p>
      <%= link_to "編集する", edit_admin_customer_path(@customer.id), class: 'btn btn-success' %>
      　　<%= link_to "注文履歴一覧を見る", admin_path(@customer.id), class: 'btn btn-primary' %>
    </div>
  </div>
</div>