config/routes.rb
Rails.application.routes.draw do
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  root to: "public/homes#top"
  get "about" => "public/homes#about"
  get "customers/my_page" => "public/customers#show"
  get "customers/information/edit" => "public/customers#edit"
  patch "customers" => "public/customers#update"

  namespace :public do
    resources :items, only: [:index, :show]
  end

  namespace :public do
    resources :customers, only: [:show, :edit, :update] do
      collection do
        get 'check'
        patch 'withdraw'
      end
    end
  end

  namespace :public do
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete 'all_destroy'
      end
    end
  end

  namespace :public do
    resources :orders, only: [:index, :new, :show, :create] do
      collection do
        get 'complete'
        post 'check'
      end
    end
  end

  get "admin" => "admin/homes#top"
  namespace :admin do
    resources :items
  end
  namespace :admin do
    resources :customers
  end
  namespace :admin do
    resources :orders, only: [:show]
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_datails, dependent: :destroy
  belongs_to :customer
  
  enum payment_method: { credit_card: 0, transfer: 1 }
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
   @order = Order.find(params[:id])
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<%= render 'admin/list' %>
<div class="container">
  <div class="row">
    <div class="col-4">
      <h4>注文履歴詳細</h4>
    </div>
  </div>

  <div class="row">
    <div class="col-2">
      <p><strong>購入者</strong></p>
      <p><strong>注文日</strong></p>
      <p><strong>配送先</strong></p>
      <p><strong>支払方法</strong></p>
    </div>
    <div class="col-6">
      <p><%= link_to @customer.full_name, admin_customer_path(cart_item.id) %></p>
      <p></p>
      <p></p>
      <p></p>
    </div>
  </div>
</div>